data:extend({
    {
        type = "assembling-machine",
        name = "Arcofolder",
        icon = "__arcotorio__/graphics/Arcofolder-icon.png",
        icon_size = 64,
        flags = {"placeable-neutral", "placeable-player", "player-creation"},
        minable = {mining_time = 1, result = "Arcofolder"},
        max_health = 300,
        corpse = "big-remnants",
        dying_explosion = "medium-explosion",
        collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
        selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
        crafting_categories = {"arcofolding"},
        crafting_speed = 1,
        energy_source = {
            type = "void"
        },
        energy_usage = "10kW",
        ingredient_count = 6,
        animation = {
            filename = "__arcotorio__/graphics/Arcofolder.png",
            height = 195,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 30,
            line_length = 5,
            shift = {x = 0 / 64, y = -0.5 / 64}
        },
        idle_animation = {
            filename = "__arcotorio__/graphics/Arcofolder-idle.png",
            height = 196,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 1,
            repeat_count = 30
        },
        allowed_effects = {"consumption", "speed", "pollution"},
    },
    {
        type = "assembling-machine",
        name = "Advanced-Arcofolder",
        icon = "__arcotorio__/graphics/advanced-arcofolder-icon.png",
        icon_size = 64,
        flags = {"placeable-neutral", "placeable-player", "player-creation"},
        minable = {mining_time = 1, result = "Advanced-Arcofolder"},
        max_health = 300,
        corpse = "big-remnants",
        dying_explosion = "medium-explosion",
        collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
        selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
        crafting_categories = {"arcofolding"},
        crafting_speed = 2,
        energy_source = {
            type = "electric",
            usage_priority = "secondary-input",
            emissions_per_minute = 0.04
        },
        energy_usage = "400kW",
        ingredient_count = 6,
        animation = {
            filename = "__arcotorio__/graphics/Arcofolder.png",
            height = 195,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 30,
            line_length = 5,
            shift = {x = 0 / 64, y = -0.5 / 64}
        },
        idle_animation = {
            filename = "__arcotorio__/graphics/Arcofolder-idle.png",
            height = 196,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 1,
            repeat_count = 30
        },
        allowed_effects = {"consumption", "speed", "pollution"},
    },
    {
        type = "assembling-machine",
        name = "McArcofolder",
        icon = "__arcotorio__/graphics/McArcofolder-icon.png",
        icon_size = 64,
        flags = {"placeable-neutral", "placeable-player", "player-creation"},
        minable = {mining_time = 1, result = "McArcofolder"},
        max_health = 300,
        corpse = "big-remnants",
        dying_explosion = "medium-explosion",
        collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
        selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
        crafting_categories = {"arcofolding"},
        crafting_speed = 4,
        energy_source = {
            type = "electric",
            usage_priority = "secondary-input",
            emissions_per_minute = 0.12
        },
        energy_usage = "1000kW",
        ingredient_count = 6,
        animation = {
            filename = "__arcotorio__/graphics/Arcofolder.png",
            height = 195,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 30,
            line_length = 5,
            shift = {x = 0 / 64, y = -0.5 / 64}
        },
        idle_animation = {
            filename = "__arcotorio__/graphics/Arcofolder-idle.png",
            height = 196,
            width = 196,
            scale = 0.5,
            animation_speed = 30,
            frame_count = 1,
            repeat_count = 30
        },
        allowed_effects = {"consumption", "speed", "pollution"},
    },
})
